name: "EventStack"

exports: "event-stack.js"

web: "[cpojer.net](http://cpojer.net)"

description: "Helps you Escape."

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [Christoph Pojer](http://cpojer.net/)"

author: "cpojer"
authors: "[Christoph Pojer](http://cpojer.net)"

sources:
    - "Source/EventStack.js"
    - "Source/EventStack.OuterClick.js"
